urls.py
""" URLConf """


from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views

from portfolio.forms.main import *
from portfolio.views.main import *

app_name = 'portfolio'

urlpatterns = [
    # Main views
    # path('', IndexView.as_view(), name='index'),
    path(
        '',
        PublicSkillListView.as_view(),
        name='index'
    ),
    path(
        'about/',
        AboutView.as_view(),
        name='about'
    ),
    path(
        'contact/',
        ContactView.as_view(),
        name='contact'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard'
    ),

    # Public views
    path(
        'badge/',
        PublicBadgeListView.as_view(),
        name='public_badge_list'
    ),
    path(
        'project/',
        PublicProjectListView.as_view(),
        name='public_project_list'
    ),
    path(
        'certificate/',
        PublicCertificateListView.as_view(),
        name='public_certificate_list'
    ),

    # Providers
    path(
        'providers/',
        ProviderListView.as_view(),
        name='provider_list'
    ),
    path(
        'providers/new/',
        ProviderCreateView.as_view(),
        name='create_provider'
    ),
    path(
        'providers/<int:pk>/edit/',
        ProviderUpdateView.as_view(),
        name='edit_provider'
    ),
    path(
        'providers/<int:pk>/delete/',
        ProviderDeletionView.as_view(),
        name='delete_provider'
    ),

    # Tags
    path(
        'tags/',
        TagListView.as_view(),
        name='tag_list'
    ),
    path(
        'tags/new/',
        TagCreateView.as_view(),
        name='create_tag'
    ),
    path(
        'tags/<int:pk>/edit/',
        TagUpdateView.as_view(),
        name='edit_tag'
    ),
    path(
        'tags/<int:pk>/delete/',
        TagDeletionView.as_view(),
        name='delete_tag'
    ),

    # Certificates
    path(
        'certificates/',
        CertificateListView.as_view(),
        name='certificate_list'
    ),
    path(
        'certificates/new/',
        CertificateCreateView.as_view(),
        name='create_certificate'
    ),
    path(
        'certificates/<int:pk>/edit/',
        CertificateUpdateView.as_view(),
        name='edit_certificate'
    ),
    path(
        'certificates/<int:pk>/delete/',
        CertificateDeletionView.as_view(),
        name='delete_certificate'
    ),

    # Badges
    path(
        'badges/',
        BadgeListView.as_view(),
        name='badge_list'
    ),
    path(
        'badges/new/',
        BadgeCreateView.as_view(),
        name='create_badge'
    ),
    path(
        'badges/<int:pk>/edit/',
        BadgeUpdateView.as_view(),
        name='edit_badge'
    ),
    path(
        'badges/<int:pk>/delete/',
        BadgeDeletionView.as_view(),
        name='delete_badge'
    ),

    # Projects
    path(
        'projects/',
        ProjectListView.as_view(),
        name='project_list'
    ),
    path(
        'projects/new/',
        ProjectCreateView.as_view(),
        name='create_project'
    ),
    path(
        'projects/<int:pk>/edit/',
        ProjectUpdateView.as_view(),
        name='edit_project'
    ),
    path(
        'projects/<int:pk>/delete/',
        ProjectDeletionView.as_view(),
        name='delete_project'
    ),
    path(
        'projects/<int:pid>/image/',
        ModelImageView.as_view(model=Project),
        name='project_image'
    ),

    # Messages
    path(
        'messages/',
        MessageListView.as_view(),
        name='message_list'
    ),
    path(
        'message/',
        MessageCreateView.as_view(),
        name='send_message'
    ),
    path(
        'messages/<int:pk>/delete/',
        MessageDeletionView.as_view(),
        name='delete_message'
    ),

    # Skills
    path(
        'skills/',
        SkillListView.as_view(),
        name='skill_list'
    ),
    path(
        'skills/new/',
        SkillCreateView.as_view(),
        name='create_skill'
    ),
    path(
        'skills/<int:pk>/edit/',
        SkillUpdateView.as_view(),
        name='edit_skill'
    ),
    path(
        'skills/<int:pk>/delete/',
        SkillDeletionView.as_view(),
        name='delete_skill'
    ),
] + [
    # Custom Authentication
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='portfolio/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreateView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:pk>/edit/',
        UserUpdateView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:pk>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='portfolio/authentication/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='profile'
    ),
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='portfolio/authentication/change_password.html',
            success_url=reverse_lazy('portfolio:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='portfolio/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='portfolio/authentication/reset_password.html',
            success_url=reverse_lazy('portfolio:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='portfolio/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='portfolio/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('portfolio:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='portfolio/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

forms/base.py
""" Base forms """


from django import forms


class StyledModelForm(forms.ModelForm):
    """ Styling the ModelForm """

    def __init__(self, *args, **kwargs):
        super(StyledModelForm, self).__init__(*args, **kwargs)
        for label in self.fields:
            field = self.fields[label]
            try:
                if field.widget.input_type in ('checkbox', 'radio'):
                    field.widget.attrs['class'] = 'form-check-input'

                elif field.widget.input_type == 'select':
                    field.widget.attrs['class'] = 'form-select'
                    field.widget.attrs['placeholder'] = field.label

                else:
                    field.widget.attrs['class'] = 'form-control'
                    field.widget.attrs['placeholder'] = field.label

            except Exception:
                field.widget.attrs['class'] = 'form-control'
                field.widget.attrs['placeholder'] = field.label

templates/portfolio/authentication/base.html
{% extends 'portfolio/base/dashboard.html' %}

templates/portfolio/authentication/change_done.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Change Done' %}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:profile' %}"> {% translate 'Profile' %} </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:change_password' %}">
      {% translate 'Password Change' %}
    </a>
  </li>
  <li class="breadcrumb-item active">{% translate 'Done' %}</li>
{% endblock %} 
{% block content %}
  <h1 class="display-1 mb-4">
    <strong> {% translate 'Password change successful' %} </strong>
  </h1>
  <p class="fs-4">{% translate 'Your password was changed.' %}</p>
  <a
    class="btn btn-lg btn-primary px-5"
    role="button"
    href="{% url 'portfolio:login' %}"
  >
    {% translate 'Login' %}
  </a>
{% endblock %}

templates/portfolio/authentication/change_password.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Change Password' %}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:profile' %}"> {% translate 'Profile' %} </a>
  </li>
  <li class="breadcrumb-item active">{% translate 'Password Change' %}</li>
{% endblock %}
{% block content %}
  <h1 class="display-1">{% translate 'Password Change' %}</h1>
  <p>
    {% blocktranslate %} 
      Please enter your old password, for security’s sake, and
      then enter your new password twice so we can verify you typed it in correctly.
    {% endblocktranslate %}
  </p>
  {% include 'portfolio/includes/utilities/form.html' with form_tag=1 method='post' floating_labels=1 %} 
  {% url 'portfolio:profile' as url %}
  {% include 'portfolio/includes/utilities/submit.html' with reset=1 cancel_url=url %} 
{% endblock %}

templates/portfolio/authentication/logged_out.html
{% extends 'portfolio/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'Logged out' %}{% endblock %}
{% block content %}
  <h1 class="display-1">
    <strong> {% translate 'Logged out' %} </strong>
  </h1>
  <p class="lead fs-3">{% translate 'Thanks for your time.' %}</p>
{% endblock %}

templates/portfolio/authentication/login.html
{% extends 'portfolio/base/base_site.html' %} 
{% load i18n %} {% block title %}{% translate 'Login' %}{% endblock %}
{% block content %}
  <h1 class="display-1">
    <strong>
      {% translate 'Welcome back!' %}
    </strong>
  </h1>
  <div class="d-flex align-items-center justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <button
            class="nav-link active"
            id="nav-signin-tab"
            data-bs-toggle="tab"
            data-bs-target="#nav-signin"
            type="button"
            role="tab"
            aria-controls="nav-signin"
            aria-selected="true"
          >
            {% translate 'Log In' %}
          </button>
          <button
            class="nav-link"
            id="nav-signup-tab"
            data-bs-toggle="tab"
            data-bs-target="#nav-signup"
            type="button"
            role="tab"
            aria-controls="nav-signup"
            aria-selected="false"
          >
            {% translate 'Register' %}
          </button>
        </div>
      </nav>
      <div
        class="card bg-dark text-white shadow rounded-b-3 border-top-0"
        style="border-top-right-radius: 0; border-top-left-radius: 0"
      >
        <div class="card-body">
          <div class="tab-content" id="nav-tabContent">
            <div
              class="tab-pane fade show active"
              id="nav-signin"
              role="tabpanel"
              aria-labelledby="nav-signin-tab"
            >
              <h1 class="text-primary mb-4">
                <strong> {% translate 'Log In' %} </strong>
              </h1>
              {% include 'portfolio/includes/utilities/form.html' with form_tag=1 method='post' floating_labels=1 %} {% url 'portfolio:index' as url %} 
              {% include 'portfolio/includes/utilities/submit.html' with form_id='form' reset=1 cancel_url=url %}
            </div>
            <div
              class="tab-pane fade"
              id="nav-signup"
              role="tabpanel"
              aria-labelledby="nav-signup-tab"
            >
              <h1 class="text-primary mb-4">
                <strong> {% translate 'Register' %} </strong>
              </h1>
              {% url 'portfolio:register' as action %}
              {% include 'portfolio/includes/utilities/form.html' with form_tag=1 form=signup_form method='post' action=action id='signup_form' floating_labels=1 %} 
              {% include 'portfolio/includes/utilities/submit.html' with form_id='signup_form' reset=1 cancel_url=url %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document
      .querySelectorAll("div.form-floating > .form-control")
      .forEach((item) => {
        item.classList.add("bg-dark", "text-white");
      });
  </script>
{% endblock %}

{% block footer %}
  <div class="container-fluid">
      {% include 'portfolio/includes/components/footer.html' with message_form=1 %}
  </div>
{% endblock %}

templates/portfolio/authentication/profile.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %} 
{% block title %}{% translate 'Profile' %}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item active">{% translate 'Profile' %}</li>
{% endblock %} 
{% block content %}
  <div class="card card-body p-4 bg-dark text-white rounded-3 shadow mb-4">
    <div class="py-5">
      <h1 class="display-1">
        <strong>
          {% translate 'Welcome ' %}{{ request.user.username }}
        </strong>
      </h1>
      <p class="lead">
        {% blocktranslate %}
          Welcome to your profile, here you will find links to
          edit, delete your account, change and reset your password. 
        {% endblocktranslate %}
      </p>
      <div class="d-lg-flex d-grid align-items-center gap-4">
        <a
          class="btn btn-outline-warning btn-lg d-inline-flex gap-4"
          href="{% url 'portfolio:edit_user' request.user.id %}"
        >
          <i class="bi bi-pencil"></i>
          {% translate 'Edit Account' %}
        </a>
        <a
          class="btn btn-outline-danger btn-lg d-inline-flex gap-4"
          href="{% url 'portfolio:delete_user' request.user.id %}"
        >
          <i class="bi bi-trash"></i>
          {% translate 'Delete Account' %}
        </a>
      </div>
    </div>
  </div>
  <div class="row align-items-md-stretch g-4">
    <div class="col-md-6">
      <div class="card card-body p-4 bg-dark text-white rounded-3 shadow">
        <h2 class="mb-4">
          <strong> {% translate 'Change the password' %} </strong>
        </h2>
        <p>
          {% blocktranslate %} 
            Here you can change your password. 
          {% endblocktranslate %}
        </p>
        <a
          href="{% url 'portfolio:change_password' %}"
          class="btn btn-outline-light btn-lg d-inline-flex gap-4"
        >
          <i class="bi bi-key"></i>
          {% translate 'Change' %}
        </a>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card card-body p-4 rounded-3 shadow">
        <h2 class="mb-4">
          <strong> {% translate 'Reset Password' %} </strong>
        </h2>
        <p>
          {% blocktranslate %}
            Or if you want to reset your password. 
          {% endblocktranslate %}
        </p>
        <a
          class="btn btn-outline-dark btn-lg d-inline-flex gap-4"
          role="button"
          href="{% url 'portfolio:reset_password' %}"
        >
          <i class="bi bi-lock"></i>
          {% translate 'Reset' %}
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/portfolio/authentication/reset_complete.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Complete' %}{% endblock %} 
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:profile' %}"> {% translate 'Profile' %} </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:reset_password' %}">
      {% translate 'Password Reset' %}
    </a>
  </li>
  <li class="breadcrumb-item">{% translate 'Complete' %}</li>
{% endblock %}
{% block content %}
  <h1 class="display-1">
    <strong> {% translate 'Password reset complete' %} </strong>
  </h1>
  <p>
    {% translate 'Your password has been set. You may go ahead and log in now.' %}
  </p>
  <a
    href="{% url 'portfolio:login' %}"
    class="btn btn-lg btn-primary px-5"
    role="button"
  >
    {% translate 'Login' %}
</a>
{% endblock %}

templates/portfolio/authentication/reset_confirm.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Confirmation' %}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:profile' %}"> {% translate 'Profile' %} </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:reset_password' %}">
      {% translate 'Password Reset' %}
    </a>
  </li>
  <li class="breadcrumb-item">{% translate 'Confirm' %}</li>
{% endblock %}
{% block content %} 
  {% if validlink %}
    <h1 class="display-1">{% translate 'Password Reset Confirm' %}</h1>
    <p>
      {% translate "Please enter your new password twice so we can verify you typed it in correctly." %}
    </p>
    {% include 'portfolio/includes/utilities/form.html' with form_tag=1 method='post' floating_labels=1 %} {% url 'portfolio:profile' as url %} 
    {% include 'portfolio/includes/utilities/submit.html' with reset=1 cancel_url=url %} 
  {% else %}
    <h1 class="display-1">
      {% translate 'The password reset link was invalid!' %}
    </h1>
    <p class="alert alert-danger">
      {% blocktranslate %}
        The password reset link was invalid, possibly because it
        has already been used. Please request a new password reset. 
      {% endblocktranslate %}
    </p>
    <a class="btn btn-lg btn-primary" href="{% url 'portfolio:reset_password' %}">
      {% translate 'Request Password Reset' %}
    </a>
  {% endif %} 
{% endblock %}

templates/portfolio/authentication/reset_done.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Password Reset Done' %}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:profile' %}"> {% translate 'Profile' %} </a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:reset_password' %}">
      {% translate 'Password Reset' %}
    </a>
  </li>
  <li class="breadcrumb-item active">{% translate 'Done' %}</li>
{% endblock %}
{% block content %}
  <h1 class="display-1 mb-4">
    <strong> {% translate 'Password reset sent' %} </strong>
  </h1>
  <p>
    {% blocktranslate %}
      We have emailed you instructions for setting your
      password, if an account exists with the email you entered. You should receive
      them shortly. If you do not receive an email, please make sure you have
      entered the address you registered with, and check your spam folder. 
    {% endblocktranslate %}
  </p>
{% endblock %}

templates/portfolio/authentication/reset_password.html
{% extends 'portfolio/authentication/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Reset Password' %}{% endblock %}
{% block breadcrumb %}
  <li class="breadcrumb-item">
    <a href="{% url 'portfolio:profile' %}"> {% translate 'Profile' %} </a>
  </li>
  <li class="breadcrumb-item active">{% translate 'Password Reset' %}</li>
{% endblock %}
{% block content %}
  <h1 class="display-1">{% translate 'Reset Password' %}</h1>
  <p>
    {% translate 'Forgotten your password? Enter your email address below, and we will email instructions for setting a new one.' %}
  </p>
  {% include 'portfolio/includes/utilities/form.html' with form_tag=1 method='post' floating_labels=1 %} {% url 'portfolio:profile' as url %} 
  {% include 'portfolio/includes/utilities/submit.html' with reset=1 cancel_url=url %} 
{% endblock %}