urls.py
""" URLConf """


from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views

from portfolio.forms.main import *
from portfolio.views.main import *

app_name = 'portfolio'

urlpatterns = [
    # Main views
    # path('', IndexView.as_view(), name='index'),
    path(
        '',
        PublicSkillListView.as_view(),
        name='index'
    ),
    path(
        'about/',
        AboutView.as_view(),
        name='about'
    ),
    path(
        'contact/',
        ContactView.as_view(),
        name='contact'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard'
    ),

    # Public views
    path(
        'badge/',
        PublicBadgeListView.as_view(),
        name='public_badge_list'
    ),
    path(
        'project/',
        PublicProjectListView.as_view(),
        name='public_project_list'
    ),
    path(
        'certificate/',
        PublicCertificateListView.as_view(),
        name='public_certificate_list'
    ),

    # Providers
    path(
        'providers/',
        ProviderListView.as_view(),
        name='provider_list'
    ),
    path(
        'providers/new/',
        ProviderCreateView.as_view(),
        name='create_provider'
    ),
    path(
        'providers/<int:pk>/edit/',
        ProviderUpdateView.as_view(),
        name='edit_provider'
    ),
    path(
        'providers/<int:pk>/delete/',
        ProviderDeletionView.as_view(),
        name='delete_provider'
    ),

    # Tags
    path(
        'tags/',
        TagListView.as_view(),
        name='tag_list'
    ),
    path(
        'tags/new/',
        TagCreateView.as_view(),
        name='create_tag'
    ),
    path(
        'tags/<int:pk>/edit/',
        TagUpdateView.as_view(),
        name='edit_tag'
    ),
    path(
        'tags/<int:pk>/delete/',
        TagDeletionView.as_view(),
        name='delete_tag'
    ),

    # Certificates
    path(
        'certificates/',
        CertificateListView.as_view(),
        name='certificate_list'
    ),
    path(
        'certificates/new/',
        CertificateCreateView.as_view(),
        name='create_certificate'
    ),
    path(
        'certificates/<int:pk>/edit/',
        CertificateUpdateView.as_view(),
        name='edit_certificate'
    ),
    path(
        'certificates/<int:pk>/delete/',
        CertificateDeletionView.as_view(),
        name='delete_certificate'
    ),

    # Badges
    path(
        'badges/',
        BadgeListView.as_view(),
        name='badge_list'
    ),
    path(
        'badges/new/',
        BadgeCreateView.as_view(),
        name='create_badge'
    ),
    path(
        'badges/<int:pk>/edit/',
        BadgeUpdateView.as_view(),
        name='edit_badge'
    ),
    path(
        'badges/<int:pk>/delete/',
        BadgeDeletionView.as_view(),
        name='delete_badge'
    ),

    # Projects
    path(
        'projects/',
        ProjectListView.as_view(),
        name='project_list'
    ),
    path(
        'projects/new/',
        ProjectCreateView.as_view(),
        name='create_project'
    ),
    path(
        'projects/<int:pk>/edit/',
        ProjectUpdateView.as_view(),
        name='edit_project'
    ),
    path(
        'projects/<int:pk>/delete/',
        ProjectDeletionView.as_view(),
        name='delete_project'
    ),
    path(
        'projects/<int:pid>/image/',
        ModelImageView.as_view(model=Project),
        name='project_image'
    ),

    # Messages
    path(
        'messages/',
        MessageListView.as_view(),
        name='message_list'
    ),
    path(
        'message/',
        MessageCreateView.as_view(),
        name='send_message'
    ),
    path(
        'messages/<int:pk>/delete/',
        MessageDeletionView.as_view(),
        name='delete_message'
    ),

    # Skills
    path(
        'skills/',
        SkillListView.as_view(),
        name='skill_list'
    ),
    path(
        'skills/new/',
        SkillCreateView.as_view(),
        name='create_skill'
    ),
    path(
        'skills/<int:pk>/edit/',
        SkillUpdateView.as_view(),
        name='edit_skill'
    ),
    path(
        'skills/<int:pk>/delete/',
        SkillDeletionView.as_view(),
        name='delete_skill'
    ),
] + [
    # Custom Authentication
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='portfolio/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreateView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:pk>/edit/',
        UserUpdateView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:pk>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='portfolio/authentication/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='profile'
    ),
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='portfolio/authentication/change_password.html',
            success_url=reverse_lazy('portfolio:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='portfolio/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='portfolio/authentication/reset_password.html',
            success_url=reverse_lazy('portfolio:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='portfolio/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='portfolio/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('portfolio:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='portfolio/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

views/list.py
""" List views """


from django.views.generic import ListView

from portfolio.views.mixins import LoginRequiredMixin, SuperUserMixin
from portfolio.models import Provider, Tag, Certificate, Badge, Project, Skill, Message


class ProviderListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Provider list view """

    model = Provider
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/provider.html'


class TagListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Tag list view """

    model = Tag
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/tag.html'


class CertificateListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Certificate list view """

    model = Certificate
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/certificate.html'


class BadgeListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Badge list view """

    model = Badge
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/badge.html'


class ProjectListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Project list view """

    model = Project
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/project.html'


class SkillListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Skill list view """

    model = Skill
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/skill.html'


class MessageListView(LoginRequiredMixin, SuperUserMixin, ListView):
    """ Message list view """

    model = Message
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/message.html'


class PublicCertificateListView(ListView):
    """ PublicCertificate list view """

    paginate_by = 10
    model = Certificate
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/public_certificate.html'


class PublicBadgeListView(ListView):
    """ PublicBadge list view """

    model = Badge
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/public_badge.html'


class PublicProjectListView(ListView):
    """ PublicProject list view """

    model = Project
    paginate_by = 10
    ordering = ('-created_at',)
    template_name = 'portfolio/views/list/public_project.html'


class PublicSkillListView(ListView):
    """ PublicSkill list view """

    model = Skill
    template_name = 'portfolio/base/index.html'

templates/portfolio/views/list/badge.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Badges' %}{% endblock %}
{% block breadcrumb_item %}{% translate 'Badges' %}{% endblock %}
{% block page_title %}{% translate 'Badges' %}{% endblock %}
{% block create_link %}{% url 'portfolio:create_badge' %}{% endblock %}
{% block table %}
    <table class="table table-dark table-hover mb-0">
        <thead>
        <tr>
            <th>
                {% translate 'ID' %}
            </th>
            <th>
                {% translate 'Name' %}
            </th>
            <th>
                {% translate 'Provider' %}
            </th>
            <th>
                {% translate 'URL' %}
            </th>
            <th>
                {% translate 'Created' %}
            </th>
            <th>
                {% translate 'Updated' %}
            </th>
            <th>
                {% translate 'Actions' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for badge in badge_list %}
            <tr>
                <td>
                    {{ badge.id }}
                </td>
                <td>
                    {{ badge.name|capfirst }}
                </td>
                <td>
                    {{ badge.provider }}
                </td>
                <td>
                    <a href="{{ badge.url }}">
                        {% translate 'View' %}
                    </a>
                </td>
                <td>
                    {{ badge.created_at }}
                </td>
                <td>
                    {{ badge.updated_at }}
                </td>
                <td>
                    <div class="d-flex align-items-center gap-4">
                        <a class="link-warning" href="{% url 'portfolio:edit_badge' badge.id %}">
                            <i class="bi bi-pencil"></i>
                            {% translate 'Edit' %}
                        </a>
                        <a class="link-danger" href="{% url 'portfolio:delete_badge' badge.id %}">
                            <i class="bi bi-trash"></i>
                            {% translate 'Delete' %}
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="7" class="text-center">
                    {% translate 'No badge found' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block count %}{{ badge_list.count }} {% translate 'Badges' %}{% endblock %}

templates/portfolio/views/list/certificate.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Certificates' %}{% endblock %}
{% block breadcrumb_item %}{% translate 'Certificates' %}{% endblock %}
{% block page_title %}{% translate 'Certificates' %}{% endblock %}
{% block create_link %}{% url 'portfolio:create_certificate' %}{% endblock %}
{% block table %}
    <table class="table table-dark table-hover mb-0">
        <thead>
        <tr>
            <th>
                {% translate 'ID' %}
            </th>
            <th>
                {% translate 'Name' %}
            </th>
            <th>
                {% translate 'Issued by' %}
            </th>
            <th>
                {% translate 'Tag' %}
            </th>
            <th>
                {% translate 'Expiration date' %}
            </th>
            <th>
                {% translate 'URL' %}
            </th>
            <th>
                {% translate 'Created' %}
            </th>
            <th>
                {% translate 'Updated' %}
            </th>
            <th>
                {% translate 'Actions' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for certificate in certificate_list %}
            <tr>
                <td>
                    {{ certificate.id }}
                </td>
                <td>
                    {{ certificate.name|capfirst }}
                </td>
                <td>
                    {{ certificate.provider }}
                </td>
                <td>
                    <span class="badge bg-{{ certificate.tag.color }}">
                        {{ certificate.tag }}
                    </span>
                </td>
                <td>
                    {% if certificate.expiration_date is None %}
                        {% translate 'No expriation date' %}
                    {% else %}
                        {{ certificate.expiration_date }}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ certificate.credential }}">
                        {% translate 'View' %}
                    </a>
                </td>
                <td>
                    {{ certificate.created_at }}
                </td>
                <td>
                    {{ certificate.updated_at }}
                </td>
                <td>
                    <div class="d-flex align-items-center gap-4">
                        <a class="link-warning" href="{% url 'portfolio:edit_certificate' certificate.id %}">
                            <i class="bi bi-pencil"></i>
                            {% translate 'Edit' %}
                        </a>
                        <a class="link-danger" href="{% url 'portfolio:delete_certificate' certificate.id %}">
                            <i class="bi bi-trash"></i>
                            {% translate 'Delete' %}
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="9" class="text-center">
                    {% translate 'No certificate found' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block count %}{{ certificate_list.count }} {% translate 'Certificates' %}{% endblock %}

templates/portfolio/views/list/message.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Messages' %}{% endblock %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">
        {% translate 'Messages' %}
    </li>
{% endblock %}
{% block content %}
    <h1 class="display-1">
        {% translate 'Messages' %}
    </h1>
    <div class="row g-4">
        {% for message in message_list %}
            <div class="col-12 col-lg-6">
                <div class="card rounded-3 shadow">
                    <div class="d-flex align-items-center justify-content-between border-bottom">
                        <div class="bg-dark text-white py-3 px-4" style="border-top-left-radius: 0.3rem;">
                            {{ message.name|slice:'0:1' }}
                        </div>
                        <div class="card-header bg-white border-bottom-0 lead">
                            {{ message.name }}
                        </div>
                        <small class="text-muted pe-3">
                            {{ message.created_at|timesince }}
                        </small>
                    </div>
                    <div class="card-body">
                        <small class="d-flex align-items-center justify-content-between text-muted mb-3">
                            <a href="mailto:{{ message.email }}">
                                {{ message.email }}
                            </a>
                            <a href="{% url 'portfolio:delete_message' message.id %}">
                                <i class="bi bi-trash"></i>
                            </a>
                        </small>
                        <p class="card-text">
                            {{ message.content }}
                        </p>
                    </div>
                </div>
            </div>
        {% empty %}
            <h2>
                {% translate 'None available' %}
            </h2>
        {% endfor %}
    </div>
{% endblock %}

templates/portfolio/views/list/project.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Projects' %}{% endblock %}
{% block breadcrumb_item %}{% translate 'Projects' %}{% endblock %}
{% block page_title %}{% translate 'Projects' %}{% endblock %}
{% block create_link %}{% url 'portfolio:create_project' %}{% endblock %}
{% block table %}
    <table class="table table-dark table-hover mb-0">
        <thead>
        <tr>
            <th>
                {% translate 'ID' %}
            </th>
            <th>
                {% translate 'Name' %}
            </th>
            <th>
                {% translate 'Status' %}
            </th>
            <th>
                {% translate 'Repo URL' %}
            </th>
            <th>
                {% translate 'Demo URL' %}
            </th>
            <th>
                {% translate 'Created' %}
            </th>
            <th>
                {% translate 'Updated' %}
            </th>
            <th>
                {% translate 'Actions' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for project in project_list %}
            <tr>
                <td>
                    {{ project.id }}
                </td>
                <td>
                    {{ project.name }}
                </td>
                <td>
                    {{ project.status }}
                </td>
                <td>
                    <a href="{{ project.url }}">
                        {% translate 'View repo' %}
                    </a>
                </td>
                <td>
                    <a href="{{ project.demo_url }}">
                        {% translate 'View demo' %}
                    </a>
                </td>
                <td>
                    {{ project.created_at }}
                </td>
                <td>
                    {{ project.updated_at }}
                </td>
                <td>
                    <div class="d-flex align-items-center gap-4">
                        <a class="link-warning" href="{% url 'portfolio:edit_project' project.id %}">
                            <i class="bi bi-pencil"></i>
                            {% translate 'Edit' %}
                        </a>
                        <a class="link-danger" href="{% url 'portfolio:delete_project' project.id %}">
                            <i class="bi bi-trash"></i>
                            {% translate 'Delete' %}
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="7" class="text-center">
                    {% translate 'No project found' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block count %}{{ project_list.count }} {% translate 'Projects' %}{% endblock %}

templates/portfolio/views/list/provider.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Providers' %}{% endblock %}
{% block breadcrumb_item %}{% translate 'Providers' %}{% endblock %}
{% block page_title %}{% translate 'Providers' %}{% endblock %}
{% block create_link %}{% url 'portfolio:create_provider' %}{% endblock %}
{% block table %}
    <table class="table table-dark table-hover mb-0">
        <thead>
        <tr>
            <th>
                {% translate 'ID' %}
            </th>
            <th>
                {% translate 'Name' %}
            </th>
            <th>
                {% translate 'URL' %}
            </th>
            <th>
                {% translate 'Created' %}
            </th>
            <th>
                {% translate 'Updated' %}
            </th>
            <th>
                {% translate 'Actions' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for provider in provider_list %}
            <tr>
                <td>
                    {{ provider.id }}
                </td>
                <td>
                    {{ provider.name }}
                </td>
                <td>
                    <a href="{{ provider.url }}">
                        {% translate 'View' %}
                    </a>
                </td>
                <td>
                    {{ provider.created_at }}
                </td>
                <td>
                    {{ provider.updated_at }}
                </td>
                <td>
                    <div class="d-flex align-items-center gap-4">
                        <a class="link-warning" href="{% url 'portfolio:edit_provider' provider.id %}">
                            <i class="bi bi-pencil"></i>
                            {% translate 'Edit' %}
                        </a>
                        <a class="link-danger" href="{% url 'portfolio:delete_provider' provider.id %}">
                            <i class="bi bi-trash"></i>
                            {% translate 'Delete' %}
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="6" class="text-center">
                    {% translate 'No provider found' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block count %}{{ provider_list.count }} {% translate 'Providers' %}{% endblock %}

templates/portfolio/views/list/public_badge.html
{% extends 'portfolio/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'My Badges' %}{% endblock %}
{% block content %}
  <div
    class="d-grid gap-4 d-lg-flex align-items-center justify-content-lg-between mb-4"
  >
    <h1 class="display-1 mb-0">{% translate 'My Badges' %}</h1>
    {% if request.user.is_superuser %}
      <a
        class="btn btn-lg btn-success d-flex gap-4"
        href="{% url 'portfolio:create_badge' %}"
      >
        <i class="bi bi-plus-lg"></i>
        {% translate 'New' %}
      </a>
    {% endif %}
  </div>
  <div class="row g-4">
    {% for badge in badge_list %}
      <div class="col-12 col-md-6 col-lg-4">
        {% include 'portfolio/includes/components/badge.html' %}
      </div>
    {% empty %}
      <div class="col-12">
        <h2 class="text-center">{% translate 'Coming soon' %}</h2>
      </div>
    {% endfor %}
  </div>
  {% if is_paginated %}
    {% include 'portfolio/includes/utilities/pagination.html' %}
  {% endif %}
{% endblock %}
{% block footer %}
  <div class="container-fluid">
    {% include 'portfolio/includes/components/footer.html' with message_form=1 %}
  </div>
{% endblock %}

templates/portfolio/views/list/public_certificate.html
{% extends 'portfolio/base/base_site.html' %}
{% load i18n %} {% block title %}{% translate 'My Certificates' %}{% endblock %} 
{% block content %}
  <div
    class="d-grid gap-4 d-lg-flex align-items-center justify-content-lg-between mb-4"
  >
    <h1 class="display-1 mb-0">{% translate 'My Certificates' %}</h1>
    {% if request.user.is_superuser %}
      <a
        class="btn btn-lg btn-danger d-flex gap-4"
        href="{% url 'portfolio:create_certificate' %}"
      >
        <i class="bi bi-plus-lg"></i>
        {% translate 'New' %}
      </a>
    {% endif %}
  </div>
  <div class="row g-4">
    {% for certificate in certificate_list %}
      <div class="col-12 col-md-6 col-lg-4">
        {% include 'portfolio/includes/components/certificate.html' %}
      </div>
    {% empty %}
      <div class="col-12">
        <h2 class="text-center">{% translate 'Coming soon' %}</h2>
      </div>
    {% endfor %}
  </div>
  {% if is_paginated %}
    {% include 'portfolio/includes/utilities/pagination.html' %}
  {% endif %}
{% endblock %}
{% block footer %}
  <div class="container-fluid">
    {% include 'portfolio/includes/components/footer.html' with message_form=1 %}
  </div>
{% endblock %}

templates/portfolio/views/list/public_project.html
{% extends 'portfolio/base/base_site.html' %}
{% load i18n %}
{% block title %}{% translate 'My Projects' %}{% endblock %}
{% block content %}
  <div
    class="d-grid gap-4 d-lg-flex align-items-center justify-content-lg-between mb-4"
  >
    <h1 class="display-1 mb-0">{% translate 'My Projects' %}</h1>
    {% if request.user.is_superuser %}
      <a
        class="btn btn-lg btn-warning d-flex gap-4"
        href="{% url 'portfolio:create_project' %}"
      >
        <i class="bi bi-plus-lg"></i>
        {% translate 'New' %}
      </a>
    {% endif %}
  </div>
  <div class="row g-4">
    {% for project in project_list %}
      <div class="col-12 col-md-6 col-lg-4">
        {% include 'portfolio/includes/components/project.html' %}
      </div>
    {% empty %}
      <div class="col-12">
        <h2 class="text-center">{% translate 'Coming soon' %}</h2>
      </div>
    {% endfor %}
  </div>
  {% if is_paginated %}
    {% include 'portfolio/includes/utilities/pagination.html' %}
  {% endif %}
{% endblock %}
{% block footer %}
  <div class="container-fluid">
    {% include 'portfolio/includes/components/footer.html' with message_form=1 %}
  </div>
{% endblock %}

templates/portfolio/views/list/skill.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Skills' %}{% endblock %}
{% block breadcrumb_item %}{% translate 'Skills' %}{% endblock %}
{% block page_title %}{% translate 'Skills' %}{% endblock %}
{% block create_link %}{% url 'portfolio:create_skill' %}{% endblock %}
{% block table %}
    <table class="table table-dark table-hover mb-0">
        <thead>
        <tr>
            <th>
                {% translate 'ID' %}
            </th>
            <th>
                {% translate 'Name' %}
            </th>
            <th>
                {% translate 'Created' %}
            </th>
            <th>
                {% translate 'Updated' %}
            </th>
            <th>
                {% translate 'Actions' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for skill in skill_list %}
            <tr>
                <td>
                    {{ skill.id }}
                </td>
                <td>
                    {{ skill.name|capfirst }}
                </td>
                <td>
                    {{ skill.created_at }}
                </td>
                <td>
                    {{ skill.updated_at }}
                </td>
                <td>
                    <div class="d-flex align-items-center gap-4">
                        <a class="link-warning" href="{% url 'portfolio:edit_skill' skill.id %}">
                            <i class="bi bi-pencil"></i>
                            {% translate 'Edit' %}
                        </a>
                        <a class="link-danger" href="{% url 'portfolio:delete_skill' skill.id %}">
                            <i class="bi bi-trash"></i>
                            {% translate 'Delete' %}
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="5" class="text-center">
                    {% translate 'No skill found' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block count %}{{ skill_list.count }} {% translate 'skills' %}{% endblock %}

templates/portfolio/views/list/tag.html
{% extends 'portfolio/views/list/template.html' %}
{% load i18n %}
{% block title %}{% translate 'Tags' %}{% endblock %}
{% block breadcrumb_item %}{% translate 'Tags' %}{% endblock %}
{% block page_title %}{% translate 'Tags' %}{% endblock %}
{% block create_link %}{% url 'portfolio:create_tag' %}{% endblock %}
{% block table %}
    <table class="table table-dark table-hover mb-0">
        <thead>
        <tr>
            <th>
                {% translate 'ID' %}
            </th>
            <th>
                {% translate 'Name' %}
            </th>
            <th>
                {% translate 'Color' %}
            </th>
            <th>
                {% translate 'Created' %}
            </th>
            <th>
                {% translate 'Updated' %}
            </th>
            <th>
                {% translate 'Actions' %}
            </th>
        </tr>
        </thead>
        <tbody>
        {% for tag in tag_list %}
            <tr>
                <td>
                    {{ tag.id }}
                </td>
                <td>
                    {{ tag.name }}
                </td>
                <td>
                    <span class="text-{{ tag.color }}">
                        {{ tag.color }}
                    </span>
                </td>
                <td>
                    {{ tag.created_at }}
                </td>
                <td>
                    {{ tag.updated_at }}
                </td>
                <td>
                    <div class="d-flex align-items-center gap-4">
                        <a class="link-warning" href="{% url 'portfolio:edit_tag' tag.id %}">
                            <i class="bi bi-pencil"></i>
                            {% translate 'Edit' %}
                        </a>
                        <a class="link-danger" href="{% url 'portfolio:delete_tag' tag.id %}">
                            <i class="bi bi-trash"></i>
                            {% translate 'Delete' %}
                        </a>
                    </div>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="6" class="text-center">
                    {% translate 'No tag found' %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block count %}{{ tag_list.count }} {% translate 'tags' %}{% endblock %}