urls.py
""" URLConf """


from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views

from portfolio.forms.main import *
from portfolio.views.main import *

app_name = 'portfolio'

urlpatterns = [
    # Main views
    # path('', IndexView.as_view(), name='index'),
    path(
        '',
        PublicSkillListView.as_view(),
        name='index'
    ),
    path(
        'about/',
        AboutView.as_view(),
        name='about'
    ),
    path(
        'contact/',
        ContactView.as_view(),
        name='contact'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard'
    ),

    # Public views
    path(
        'badge/',
        PublicBadgeListView.as_view(),
        name='public_badge_list'
    ),
    path(
        'project/',
        PublicProjectListView.as_view(),
        name='public_project_list'
    ),
    path(
        'certificate/',
        PublicCertificateListView.as_view(),
        name='public_certificate_list'
    ),

    # Providers
    path(
        'providers/',
        ProviderListView.as_view(),
        name='provider_list'
    ),
    path(
        'providers/new/',
        ProviderCreateView.as_view(),
        name='create_provider'
    ),
    path(
        'providers/<int:pk>/edit/',
        ProviderUpdateView.as_view(),
        name='edit_provider'
    ),
    path(
        'providers/<int:pk>/delete/',
        ProviderDeletionView.as_view(),
        name='delete_provider'
    ),

    # Tags
    path(
        'tags/',
        TagListView.as_view(),
        name='tag_list'
    ),
    path(
        'tags/new/',
        TagCreateView.as_view(),
        name='create_tag'
    ),
    path(
        'tags/<int:pk>/edit/',
        TagUpdateView.as_view(),
        name='edit_tag'
    ),
    path(
        'tags/<int:pk>/delete/',
        TagDeletionView.as_view(),
        name='delete_tag'
    ),

    # Certificates
    path(
        'certificates/',
        CertificateListView.as_view(),
        name='certificate_list'
    ),
    path(
        'certificates/new/',
        CertificateCreateView.as_view(),
        name='create_certificate'
    ),
    path(
        'certificates/<int:pk>/edit/',
        CertificateUpdateView.as_view(),
        name='edit_certificate'
    ),
    path(
        'certificates/<int:pk>/delete/',
        CertificateDeletionView.as_view(),
        name='delete_certificate'
    ),

    # Badges
    path(
        'badges/',
        BadgeListView.as_view(),
        name='badge_list'
    ),
    path(
        'badges/new/',
        BadgeCreateView.as_view(),
        name='create_badge'
    ),
    path(
        'badges/<int:pk>/edit/',
        BadgeUpdateView.as_view(),
        name='edit_badge'
    ),
    path(
        'badges/<int:pk>/delete/',
        BadgeDeletionView.as_view(),
        name='delete_badge'
    ),

    # Projects
    path(
        'projects/',
        ProjectListView.as_view(),
        name='project_list'
    ),
    path(
        'projects/new/',
        ProjectCreateView.as_view(),
        name='create_project'
    ),
    path(
        'projects/<int:pk>/edit/',
        ProjectUpdateView.as_view(),
        name='edit_project'
    ),
    path(
        'projects/<int:pk>/delete/',
        ProjectDeletionView.as_view(),
        name='delete_project'
    ),
    path(
        'projects/<int:pid>/image/',
        ModelImageView.as_view(model=Project),
        name='project_image'
    ),

    # Messages
    path(
        'messages/',
        MessageListView.as_view(),
        name='message_list'
    ),
    path(
        'message/',
        MessageCreateView.as_view(),
        name='send_message'
    ),
    path(
        'messages/<int:pk>/delete/',
        MessageDeletionView.as_view(),
        name='delete_message'
    ),

    # Skills
    path(
        'skills/',
        SkillListView.as_view(),
        name='skill_list'
    ),
    path(
        'skills/new/',
        SkillCreateView.as_view(),
        name='create_skill'
    ),
    path(
        'skills/<int:pk>/edit/',
        SkillUpdateView.as_view(),
        name='edit_skill'
    ),
    path(
        'skills/<int:pk>/delete/',
        SkillDeletionView.as_view(),
        name='delete_skill'
    ),
] + [
    # Custom Authentication
    path(
        'accounts/login/',
        views.LoginView.as_view(
            form_class=StyledAuthenticationForm,
            template_name='portfolio/authentication/login.html',
            extra_context={
                'signup_form': StyledUserCreationForm()
            }
        ),
        name='login'
    ),
    path(
        'accounts/register/',
        UserCreateView.as_view(),
        name='register'
    ),
    path(
        'accounts/<int:pk>/edit/',
        UserUpdateView.as_view(),
        name='edit_user'
    ),
    path(
        'accounts/<int:pk>/delete/',
        UserDeletionView.as_view(),
        name='delete_user'
    ),
    path(
        'accounts/logout/',
        views.LogoutView.as_view(
            template_name='portfolio/authentication/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'accounts/profile/',
        ProfileView.as_view(),
        name='profile'
    ),
    path(
        'accounts/password/change/',
        views.PasswordChangeView.as_view(
            form_class=StyledPasswordChangeForm,
            template_name='portfolio/authentication/change_password.html',
            success_url=reverse_lazy('portfolio:change_done')
        ),
        name='change_password'
    ),
    path(
        'accounts/password/change/done/',
        views.PasswordChangeDoneView.as_view(
            template_name='portfolio/authentication/change_done.html'
        ),
        name='change_done'
    ),
    path(
        'accounts/password/reset/',
        views.PasswordResetView.as_view(
            form_class=StyledPasswordResetForm,
            template_name='portfolio/authentication/reset_password.html',
            success_url=reverse_lazy('portfolio:reset_done')
        ),
        name='reset_password'
    ),
    path(
        'accounts/password/reset/done/',
        views.PasswordResetDoneView.as_view(
            template_name='portfolio/authentication/reset_done.html'
        ),
        name='reset_done'
    ),
    path(
        'accounts/password/reset/confirm/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(
            template_name='portfolio/authentication/reset_confirm.html',
            form_class=StyledPasswordResetForm,
            success_url=reverse_lazy('portfolio:reset_complete')
        ),
        name='reset_confirm'
    ),
    path(
        'accounts/password/reset/complete/',
        views.PasswordResetCompleteView.as_view(
            template_name='portfolio/authentication/reset_complete.html',
        ),
        name='reset_complete'
    ),
]

templates/portfolio/includes/components/footer.html
{% load i18n %}
<div class="mt-4">
    <footer class="card card-body mb-3 rounded-3 shadow bg-dark text-white p-4 shadow-lg">
        <a href="{% url 'portfolio:index' %}" class="display-4 mb-4">
            {% spaceless %}
                <span class="fw-bold">
                    <span class="text-primary">Y</span>
                    <span class="text-danger">o</span>
                    <span class="text-warning">u</span>
                    <span class="text-primary">z</span>
                    <span class="text-success">a</span>
                    <span class="text-danger">r</span>
                    <span class="text-primary">s</span>
                    <span class="text-danger">i</span>
                    <span class="text-warning">p</span>
                    <span class="text-primary">h</span>
                </span>
            {% endspaceless %}
        </a>
        <div class="row g-4">
            <div class="col-6 col-md-3 mb-3">
                <h4 class="lead fs-4">
                    {% translate 'Home' %}
                </h4>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="{% url 'portfolio:index' %}" class="nav-link p-0 text-muted">
                            {% translate 'Home' %}
                        </a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'portfolio:public_certificate_list' %}" class="nav-link p-0 text-muted">
                            {% translate 'Certificates' %}
                        </a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'portfolio:public_badge_list' %}" class="nav-link p-0 text-muted">
                            {% translate 'Badges' %}
                        </a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'portfolio:public_project_list' %}" class="nav-link p-0 text-muted">
                            {% translate 'Projects' %}
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-6 col-md-3 mb-3">
                <h4 class="lead fs-4">
                    {% translate 'About' %}
                </h4>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2">
                        <a href="{% url 'portfolio:about' %}" class="nav-link p-0 text-muted">
                            {% translate 'About Me' %}
                        </a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="{% url 'portfolio:contact' %}" class="nav-link p-0 text-muted">
                            {% translate 'Contact' %}
                        </a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="mailto:" class="nav-link p-0 text-muted">
                            {% translate 'Send an email' %}
                        </a>
                    </li>
                    <li class="nav-item mb-2">
                        <a href="#" class="nav-link p-0 text-muted">
                            {% translate 'FAQs' %}
                        </a>
                    </li>
                </ul>
            </div>
            {% if message_form %}
                <div class="col-md-5 offset-md-1 mb-3">
                    <h5 class="lead fs-5">
                        {% translate 'Have a question?' %}
                    </h5>
                    <p>
                        {% translate 'Send a message and we will reply as soon as possible.' %}
                    </p>
                    <a href="{% url 'portfolio:send_message' %}" class="btn btn-outline-primary shadow">
                        {% translate 'Send a message' %}
                    </a>
                </div>
            {% endif %}
        </div>
        <p class="small">
            © {% translate '2022 Yousef Abu Shanab. All rights reserved.' %}
        </p>
    </footer>
</div>

templates/portfolio/includes/components/messages.html
<ul class="list-unstyled mb-0">
    {% for message in messages %}
        <li>
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show d-flex align-items-center gap-4" role="alert">
                <span class="badge bg-{% if message.tags %}{{ message.tags }}{% endif %} rounded-pill">
                    {{ message.tags|capfirst }}
                </span>
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </li>
    {% endfor %}
</ul>

templates/portfolio/includes/components/navbar.html
{% load i18n %}
<nav
  class="navbar navbar-{{ color|default:'dark' }} bg-{{ bg_color|default:'primary' }} navbar-expand-{{ expand_at|default:'lg' }} p-3 rounded-3 shadow"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'portfolio:index' %}">
      {% spaceless %}
        <span class="fw-bold">
          <span class="text-white">Y</span>
          <span class="text-danger">o</span>
          <span class="text-warning">u</span>
          <span class="text-white">z</span>
          <span class="text-success">a</span>
          <span class="text-danger">r</span>
          <span class="text-white">s</span>
          <span class="text-danger">i</span>
          <span class="text-warning">p</span>
          <span class="text-white">h</span>
        </span>
      {% endspaceless %}
    </a>
    <button
      class="navbar-toggler collapsed p-2 rounded-circle"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbar"
      aria-controls="navbar"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          {% url 'portfolio:index' as home %}
          <a
            class="nav-link d-flex gap-4 gap-lg-2{% if request.path == home %} active{% endif %}"
            href="{{ home }}"
          >
            <i class="bi bi-house-fill"></i>
            {% translate 'Home' %}
          </a>
        </li>
        <li class="nav-item">
          {% url 'portfolio:public_certificate_list' as certificates %}
          <a
            class="nav-link d-flex gap-4 gap-lg-2{% if request.path == certificates %} active{% endif %}"
            href="{{ certificates }}"
          >
            <i class="bi bi-list-stars"></i>
            {% translate 'Certificates' %}
          </a>
        </li>
        <li class="nav-item">
          {% url 'portfolio:public_badge_list' as badges %}
          <a
            class="nav-link d-flex gap-4 gap-lg-2{% if request.path == badges %} active{% endif %}"
            href="{{ badges }}"
          >
            <i class="bi bi-person-badge-fill"></i>
            {% translate 'Badges' %}
          </a>
        </li>
        <li class="nav-item">
          {% url 'portfolio:public_project_list' as projects %}
          <a
            class="nav-link d-flex gap-4 gap-lg-2{% if request.path == projects %} active{% endif %}"
            href="{{ projects }}"
          >
            <i class="bi bi-journal-code"></i>
            {% translate 'Projects' %}
          </a>
        </li>
        <li class="nav-item">
          {% url 'portfolio:about' as about %}
          <a
            class="nav-link d-flex gap-4 gap-lg-2{% if request.path == about %} active{% endif %}"
            href="{{ about }}"
          >
            <i class="bi bi-info-circle-fill"></i>
            {% translate 'About' %}
          </a>
        </li>
        <li class="nav-item">
          {% url 'portfolio:contact' as contact %}
          <a
            class="nav-link d-flex gap-4 gap-lg-2{% if request.path == contact %} active{% endif %}"
            href="{{ contact }}"
          >
            <i class="bi bi-envelope-fill"></i>
            {% translate 'Contact' %}
          </a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a
            class="nav-link d-flex gap-4 gap-lg-2"
            href="#"
            data-bs-toggle="dropdown"
          >
            <i class="bi bi-person-circle"></i>
            {% translate 'Profile' %}
          </a>
          <div class="dropdown-menu rounded-3 shadow">
            <div class="dropdown-header">{% translate 'Account Menu' %}</div>
            <a class="dropdown-item" href="{% url 'portfolio:profile' %}">
              <div class="dropdown-item-text d-flex gap-4">
                <i class="bi bi-person"></i>
                {% translate 'Account' %}
              </div>
            </a>
            {% if request.user.is_superuser %}
              <a class="dropdown-item" href="{% url 'portfolio:dashboard' %}">
                <div class="dropdown-item-text d-flex gap-4">
                  <i class="bi bi-gear"></i>
                  {% translate 'Dashbaord' %}
                </div>
              </a>
            {% endif %}
            {% if request.user.is_authenticated %}
              <a class="dropdown-item" href="{% url 'portfolio:logout' %}">
                <div class="dropdown-item-text d-flex gap-4">
                  <i class="bi bi-power"></i>
                  {% translate 'Logout' %}
                </div>
              </a>
            {% else %}
              <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#modalSignin">
                <div class="dropdown-item-text d-flex gap-4">
                  <i class="bi bi-box-arrow-in-right"></i>
                  {% translate 'Login' %}
                </div>
              </a>
            {% endif %}
          </div>
        </li>
        <li class="nav-item">
          <a
            class="nav-link d-flex gap-4 gap-lg-2"
            href="https://github.com/youzarsiph/"
          >
            <i class="bi bi-github"></i>
            {% translate 'Github' %}
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link d-flex gap-4 gap-lg-2"
            href="https://www.linkedin.com/in/youzarsiph/"
          >
            <i class="bi bi-linkedin"></i>
            {% translate 'LinkedIn' %}
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div tabindex="-1" role="dialog" id="modalSignin" class="modal py-5">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow bg-dark text-white">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <h2 class="fw-bold mb-0">{% translate 'Log In' %}</h2>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>

      <div class="modal-body p-5 pt-0">
        <form action="{% url 'portfolio:login' %}" method="post">
          {% csrf_token %}
          <div class="form-floating mb-3">
            <input
              type="text"
              name="username"
              class="form-control bg-dark text-white rounded-3"
              id="floatingInput"
              placeholder="name@example.com"
            />
            <label for="floatingInput">{% translate 'Username' %}</label>
          </div>
          <div class="form-floating mb-3">
            <input
              type="password"
              name="password"
              class="form-control bg-dark text-white rounded-3"
              id="floatingPassword"
              placeholder="Password"
            />
            <label for="floatingPassword">{% translate 'Password' %}</label>
          </div>
          <button
            class="w-100 mb-2 btn btn-lg rounded-3 btn-outline-primary"
            type="submit"
          >
            {% translate 'Login' %}
          </button>
          <small class="text-muted">
            {% translate 'By clicking Sign in, you agree to the terms of use.' %}
          </small>
        </form>
      </div>
    </div>
  </div>
</div>

templates/portfolio/includes/components/sidebar.html
{% load i18n %}
<aside class="navbar navbar-{{ color|default:'dark' }} bg-{{ bg_color|default:'primary' }} navbar-expand-{{ expand_at|default:'lg' }} align-items-lg-start h-100 rounded-3 shadow"
       aria-label="Side bar">
    <div class="container-fluid flex-lg-column align-items-lg-start h-100 w-100">
        <button class="navbar-toggler rounded-circle p-2" type="button" data-bs-toggle="offcanvas"
                data-bs-target="#sidebar"
                aria-controls="sidebar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand me-0" href="#">
            {% translate 'Dashboard' %}
        </a>
        <div class="navbar-nav d-lg-none">
            <a class="nav-link px-3 p-lg-2{% if request.path == profile %} active{% endif %}"
               href="{% url 'portfolio:profile' %}">
                <i class="bi bi-person-circle"></i>
            </a>
        </div>
        <div class="offcanvas offcanvas-end text-white bg-{{ bg_color|default:'primary' }}" tabindex="-1" id="sidebar"
             aria-labelledby="sidebarLabel" style="width: 100% !important;">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="sidebarLabel">
                    {% translate 'Dashboard' %}
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
            </div>
            <div class="offcanvas-body d-flex flex-column justify-content-between h-100">
                <ul class="navbar-nav flex-lg-column w-100">
                    <li class="nav-item">
                        {% url 'portfolio:dashboard' as dashboard %}
                        <a class="nav-link d-flex gap-4{% if request.path == dashboard %} active{% endif %}"
                           href="{{ dashboard }}">
                            <i class="bi bi-gear-fill"></i>
                            {% translate 'Dashboard' %}
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link d-flex gap-4" href="#" data-bs-toggle="dropdown">
                            <i class="bi bi-stack"></i>
                            {% translate 'Providers' %}
                        </a>
                        <div class="dropdown-menu position-lg-static rounded-3 shadow">
                            <div class="dropdown-header">
                                {% translate 'Provider Menu' %}
                            </div>
                            <a class="dropdown-item" href="{% url 'portfolio:provider_list' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-eye"></i>
                                    {% translate 'View' %}
                                </div>
                            </a>
                            <a class="dropdown-item" href="{% url 'portfolio:create_provider' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-plus-lg"></i>
                                    {% translate 'Create' %}
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link d-flex gap-4" href="#" data-bs-toggle="dropdown">
                            <i class="bi bi-link"></i>
                            {% translate 'Tags' %}
                        </a>
                        <div class="dropdown-menu position-lg-static rounded-3 shadow">
                            <div class="dropdown-header">
                                {% translate 'Tag Menu' %}
                            </div>
                            <a class="dropdown-item" href="{% url 'portfolio:tag_list' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-eye"></i>
                                    {% translate 'View' %}
                                </div>
                            </a>
                            <a class="dropdown-item" href="{% url 'portfolio:create_tag' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-plus-lg"></i>
                                    {% translate 'Create' %}
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link d-flex gap-4" href="#" data-bs-toggle="dropdown">
                            <i class="bi bi-list-stars"></i>
                            {% translate 'Certificates' %}
                        </a>
                        <div class="dropdown-menu position-lg-static rounded-3 shadow">
                            <div class="dropdown-header">
                                {% translate 'Certificate Menu' %}
                            </div>
                            <a class="dropdown-item" href="{% url 'portfolio:certificate_list' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-eye"></i>
                                    {% translate 'View' %}
                                </div>
                            </a>
                            <a class="dropdown-item" href="{% url 'portfolio:create_certificate' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-plus-lg"></i>
                                    {% translate 'Create' %}
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link d-flex gap-4" href="#" data-bs-toggle="dropdown">
                            <i class="bi bi-person-badge-fill"></i>
                            {% translate 'Badges' %}
                        </a>
                        <div class="dropdown-menu position-lg-static rounded-3 shadow">
                            <div class="dropdown-header">
                                {% translate 'Badge Menu' %}
                            </div>
                            <a class="dropdown-item" href="{% url 'portfolio:badge_list' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-eye"></i>
                                    {% translate 'View' %}
                                </div>
                            </a>
                            <a class="dropdown-item" href="{% url 'portfolio:create_badge' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-plus-lg"></i>
                                    {% translate 'Create' %}
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link d-flex gap-4" href="#" data-bs-toggle="dropdown">
                            <i class="bi bi-code-square"></i>
                            {% translate 'Projects' %}
                        </a>
                        <div class="dropdown-menu position-lg-static rounded-3 shadow">
                            <div class="dropdown-header">
                                {% translate 'Project Menu' %}
                            </div>
                            <a class="dropdown-item" href="{% url 'portfolio:project_list' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-eye"></i>
                                    {% translate 'View' %}
                                </div>
                            </a>
                            <a class="dropdown-item" href="{% url 'portfolio:create_project' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-plus-lg"></i>
                                    {% translate 'Create' %}
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link d-flex gap-4" href="#" data-bs-toggle="dropdown">
                            <i class="bi bi-link"></i>
                            {% translate 'Skills' %}
                        </a>
                        <div class="dropdown-menu position-lg-static rounded-3 shadow">
                            <div class="dropdown-header">
                                {% translate 'Skill Menu' %}
                            </div>
                            <a class="dropdown-item" href="{% url 'portfolio:skill_list' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-eye"></i>
                                    {% translate 'View' %}
                                </div>
                            </a>
                            <a class="dropdown-item" href="{% url 'portfolio:create_skill' %}">
                                <div class="dropdown-item-text d-flex align-items-center gap-4">
                                    <i class="bi bi-plus-lg"></i>
                                    {% translate 'Create' %}
                                </div>
                            </a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center gap-4" href="{% url 'portfolio:message_list' %}">
                            <i class="bi bi-chat-fill"></i>
                            {% translate 'Messages' %}
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav flex-column">
                    <li class="nav-item">
                        {% url 'portfolio:profile' as profile %}
                        <a class="nav-link d-flex gap-4{% if request.path == profile %} active{% endif %}"
                           href="{{ profile }}">
                            <i class="bi bi-person-circle"></i>
                            {% translate 'Account' %}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex gap-4" href="{% url 'portfolio:logout' %}">
                            <i class="bi bi-power"></i>
                            {% translate 'Log out' %}
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</aside>